#!/usr/bin/env -S node
import type { Contract as End } from '../../snapshots/3da8eac623684af82c16039df326d8ff7b2ad0cb5eaa780663d86f6c75de77f0/contract';
import endContract from '../../snapshots/3da8eac623684af82c16039df326d8ff7b2ad0cb5eaa780663d86f6c75de77f0/contract.json' with { type: 'json' };
import {
  Migration,
  MigrationCLI,
  checkExpression,
  col,
  fn,
  lit,
  primaryKey,
} from '@internal/postgres/migration';

export default class M extends Migration<never, End> {
  override readonly endContractJson = endContract;

  override get operations() {
    return [
      this.createSchema({ schema: 'public' }),
      this.createTable({
        schema: 'public',
        table: 'auditLog',
        columns: [
          col('action', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('context', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('date', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('entityId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('entityType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('ipAddress', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('newValues', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('oldValues', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('userId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'contactMessage',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('email', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('message', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('phone', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('NEW'),
            codecRef: { codecId: 'pg/text@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'contactMessage_status_check_4518e741',
            "\"status\" IN ('NEW', 'READ', 'REPLIED', 'ARCHIVED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'contentPage',
        columns: [
          col('content', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('isPublished', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('seo', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('slug', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('title', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'customer',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('email', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('firstName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('lastName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('phone', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('whatsapp', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'delivery',
        columns: [
          col('actualTime', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('destinationId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('incidents', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('instructions', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('managerId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('missionId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('plannedTime', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('reservationId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('siteContactName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('siteContactPhone', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('PLANNED'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'delivery_status_check_fba5e1b9',
            "\"status\" IN ('PLANNED', 'EN_ROUTE', 'DELIVERED', 'RETURNED', 'FAILED')",
          ),
          checkExpression('delivery_type_check_b5337bb0', "\"type\" IN ('OUTBOUND', 'INBOUND')"),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'deliveryItem',
        columns: [
          col('condition', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('deliveryId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('equipmentId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('inventoryId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('quantity', 'int4', {
            notNull: true,
            default: lit(1),
            codecRef: { codecId: 'pg/int4@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'documentTemplate',
        columns: [
          col('content', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'documentTemplate_type_check_eaf18084',
            "\"type\" IN ('INVOICE', 'CONTRACT', 'QUOTE')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'equipment',
        columns: [
          col('categoryId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('minStockThreshold', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('totalGlobalQuantity', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'equipmentCategory',
        columns: [
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'equipmentMaintenance',
        columns: [
          col('cost', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('inventoryId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('issueDescription', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('responsibleId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('returnDate', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('startDate', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'equipmentMaintenance_status_check_2e842c7c',
            "\"status\" IN ('PENDING', 'IN_PROGRESS', 'RESOLVED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'equipmentStatusHistory',
        columns: [
          col('changedById', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('date', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('inventoryId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('newStatus', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('oldStatus', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('reason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'equipmentStatusHistory_newStatus_check_851024d2',
            "\"newStatus\" IN ('AVAILABLE', 'IN_USE', 'IN_MAINTENANCE', 'LOST')",
          ),
          checkExpression(
            'equipmentStatusHistory_oldStatus_check_ad4c2533',
            "\"oldStatus\" IN ('AVAILABLE', 'IN_USE', 'IN_MAINTENANCE', 'LOST')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'formula',
        columns: [
          col('availability', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('capacity', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('conditions', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('duration', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('price', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('serviceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'gallery',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'galleryItem',
        columns: [
          col('galleryId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('mediaId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('order', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'importError',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('errorDetail', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('importJobId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('rawData', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('rowNumber', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'importJob',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('entityType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('processedRows', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('totalRows', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'importJob_status_check_48358bb5',
            "\"status\" IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'inventory',
        columns: [
          col('equipmentId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('quantity', 'int4', {
            notNull: true,
            default: lit(1),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('status', 'text', {
            notNull: true,
            default: lit('AVAILABLE'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('storageLocationId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'inventory_status_check_1657f4be',
            "\"status\" IN ('AVAILABLE', 'IN_USE', 'IN_MAINTENANCE', 'LOST')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'inventoryAllocation',
        columns: [
          col('endDate', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('inventoryId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('quantityAllocated', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('reservationId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('startDate', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('status', 'text', {
            notNull: true,
            default: lit('RESERVED'),
            codecRef: { codecId: 'pg/text@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'inventoryAllocation_status_check_08c2369b',
            "\"status\" IN ('RESERVED', 'DEPLOYED', 'RETURNED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'inventoryMovement',
        columns: [
          col('date', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('fromStorageLocationId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('inventoryId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('quantity', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('reason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('referenceId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('referenceType', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('toStorageLocationId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('userId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'inventoryMovement_type_check_705a8c12',
            "\"type\" IN ('IN', 'OUT', 'TRANSFER', 'ADJUSTMENT', 'MAINTENANCE', 'LOST', 'RETURN')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'invoice',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('customerId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('dueDate', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('issueDate', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('number', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('reservationId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('DRAFT'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('subtotal', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('taxAmount', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('totalAmount', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'invoice_status_check_6cdc860a',
            "\"status\" IN ('DRAFT', 'ISSUED', 'PAID', 'CANCELLED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'invoiceItem',
        columns: [
          col('description', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('formulaId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('invoiceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('quantity', 'int4', {
            notNull: true,
            default: lit(1),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('totalPrice', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('unitPrice', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'location',
        columns: [
          col('accessInstructions', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('city', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('commune', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('contactPhone', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('country', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('customerId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('detailedAddress', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('isChateau', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('landmark', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('latitude', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('longitude', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('name', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('neighborhood', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('precision', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('region', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'logisticsHistory',
        columns: [
          col('changedById', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('date', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('missionId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('newStatus', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('oldStatus', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'logisticsHistory_newStatus_check_19495c99',
            "\"newStatus\" IN ('A_PLANIFIER', 'PLANIFIEE', 'EN_PREPARATION', 'EN_COURS', 'TERMINEE', 'ANNULEE', 'INCIDENT')",
          ),
          checkExpression(
            'logisticsHistory_oldStatus_check_762a4243',
            "\"oldStatus\" IN ('A_PLANIFIER', 'PLANIFIEE', 'EN_PREPARATION', 'EN_COURS', 'TERMINEE', 'ANNULEE', 'INCIDENT')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'logisticsMission',
        columns: [
          col('assignedUserId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('incidents', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('reservationId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('scheduledDate', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('status', 'text', {
            notNull: true,
            default: lit('A_PLANIFIER'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'logisticsMission_status_check_44f07a2f',
            "\"status\" IN ('A_PLANIFIER', 'PLANIFIEE', 'EN_PREPARATION', 'EN_COURS', 'TERMINEE', 'ANNULEE', 'INCIDENT')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'loyaltyAccount',
        columns: [
          col('currentPoints', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('customerId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('joinedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('loyaltyLevelId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('totalPointsEarned', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'loyaltyLevel',
        columns: [
          col('benefitsDescription', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('pointsThreshold', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'loyaltyReward',
        columns: [
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('pointsCost', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'loyaltyTransaction',
        columns: [
          col('accountId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('date', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('points', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('referenceId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('rewardId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'loyaltyTransaction_type_check_bb61f4b2',
            "\"type\" IN ('EARN', 'REDEEM')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'media',
        columns: [
          col('altText', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('fileName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('mimeType', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('sizeBytes', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('storagePath', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('url', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'media_type_check_7891ea4f',
            "\"type\" IN ('IMAGE', 'VIDEO', 'DOCUMENT')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'notification',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('message', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('read', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('title', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'notification_type_check_cc0e2314',
            "\"type\" IN ('SYSTEM', 'REMINDER', 'PROMO')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'payment',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('reservationId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('totalExpected', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('totalPaid', 'numeric', {
            notNull: true,
            default: lit('0'),
            codecRef: { codecId: 'pg/numeric@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'payment_status_check_df09fd67',
            "\"status\" IN ('PENDING', 'PARTIAL', 'PAID', 'PARTIAL_REFUNDED', 'FULLY_REFUNDED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'paymentTransaction',
        columns: [
          col('amount', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('date', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('method', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('paymentId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('transactionReference', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'paymentTransaction_method_check_1ecd3a38',
            "\"method\" IN ('CASH', 'CARD', 'MOBILE_MONEY', 'BANK_TRANSFER', 'CHEQUE')",
          ),
          checkExpression(
            'paymentTransaction_status_check_f32a67f1',
            "\"status\" IN ('PENDING', 'SUCCESS', 'FAILED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'paymentTransactionHistory',
        columns: [
          col('date', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('newStatus', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('oldStatus', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('transactionId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'paymentTransactionHistory_newStatus_check_141b1df9',
            "\"newStatus\" IN ('PENDING', 'SUCCESS', 'FAILED')",
          ),
          checkExpression(
            'paymentTransactionHistory_oldStatus_check_8a48e609',
            "\"oldStatus\" IN ('PENDING', 'SUCCESS', 'FAILED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'permission',
        columns: [
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'refund',
        columns: [
          col('amount', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('date', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('paymentTransactionId', 'text', {
            notNull: true,
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('reason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'reservation',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('customerId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('endDate', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('locationId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('locationType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('participants', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('paymentStatus', 'text', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('reference', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('startDate', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('status', 'text', {
            notNull: true,
            default: lit('DRAFT'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('totalAmount', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'reservation_locationType_check_42c3f8b3',
            "\"locationType\" IN ('VENUE', 'CUSTOMER_ADDRESS', 'OTHER_LOCATION')",
          ),
          checkExpression(
            'reservation_paymentStatus_check_29030a90',
            "\"paymentStatus\" IN ('PENDING', 'PARTIAL', 'PAID', 'PARTIAL_REFUNDED', 'FULLY_REFUNDED')",
          ),
          checkExpression(
            'reservation_status_check_9b91110c',
            "\"status\" IN ('DRAFT', 'CONFIRMED', 'COMPLETED', 'CANCELLED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'reservationItem',
        columns: [
          col('formulaId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('quantity', 'int4', {
            notNull: true,
            default: lit(1),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('reservationId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('totalPrice', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('unitPrice', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'reservationStatusHistory',
        columns: [
          col('changedById', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('date', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('newStatus', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('oldStatus', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('reason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('reservationId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'reservationStatusHistory_newStatus_check_b0e24a0d',
            "\"newStatus\" IN ('DRAFT', 'CONFIRMED', 'COMPLETED', 'CANCELLED')",
          ),
          checkExpression(
            'reservationStatusHistory_oldStatus_check_b8deddf7',
            "\"oldStatus\" IN ('DRAFT', 'CONFIRMED', 'COMPLETED', 'CANCELLED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'role',
        columns: [
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'rolePermission',
        columns: [
          col('permissionId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('roleId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['roleId', 'permissionId'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'service',
        columns: [
          col('availability', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('basePrice', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('capacity', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('categoryId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('conditions', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('duration', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('images', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'serviceCategory',
        columns: [
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'serviceResource',
        columns: [
          col('equipmentId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('formulaId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('requiredQuantity', 'int4', {
            notNull: true,
            default: lit(1),
            codecRef: { codecId: 'pg/int4@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'siteSettings',
        columns: [
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('key', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('value', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'storageLocation',
        columns: [
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'user',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('customerId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('email', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('isActive', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('name', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('role', 'text', {
            notNull: true,
            default: lit('CLIENT'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'user_role_check_22a1f566',
            "\"role\" IN ('ADMIN', 'SUPERVISOR', 'SECRETARY', 'LOGISTICIAN', 'CLIENT')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'userRoleAssignment',
        columns: [
          col('roleId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['userId', 'roleId'])],
      }),
      this.addUnique({
        schema: 'public',
        table: 'contentPage',
        constraint: 'contentPage_slug_key',
        columns: ['slug'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'customer',
        constraint: 'customer_email_key',
        columns: ['email'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'equipmentCategory',
        constraint: 'equipmentCategory_name_key',
        columns: ['name'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'galleryItem',
        constraint: 'galleryItem_galleryId_mediaId_key',
        columns: ['galleryId', 'mediaId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'invoice',
        constraint: 'invoice_number_key',
        columns: ['number'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'loyaltyAccount',
        constraint: 'loyaltyAccount_customerId_key',
        columns: ['customerId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'loyaltyLevel',
        constraint: 'loyaltyLevel_name_key',
        columns: ['name'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'payment',
        constraint: 'payment_reservationId_key',
        columns: ['reservationId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'paymentTransaction',
        constraint: 'paymentTransaction_transactionReference_key',
        columns: ['transactionReference'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'permission',
        constraint: 'permission_name_key',
        columns: ['name'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'reservation',
        constraint: 'reservation_reference_key',
        columns: ['reference'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'role',
        constraint: 'role_name_key',
        columns: ['name'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'serviceCategory',
        constraint: 'serviceCategory_name_key',
        columns: ['name'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'serviceResource',
        constraint: 'serviceResource_formulaId_equipmentId_key',
        columns: ['formulaId', 'equipmentId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'siteSettings',
        constraint: 'siteSettings_key_key',
        columns: ['key'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'storageLocation',
        constraint: 'storageLocation_name_key',
        columns: ['name'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'user',
        constraint: 'user_email_key',
        columns: ['email'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'user',
        constraint: 'user_customerId_key',
        columns: ['customerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'auditLog',
        index: 'auditLog_date_idx_b4ca319c',
        columns: ['date'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'auditLog',
        index: 'auditLog_entityType_entityId_idx_ea0fa809',
        columns: ['entityType', 'entityId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'auditLog',
        index: 'auditLog_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'customer',
        index: 'customer_whatsapp_idx_d47eed42',
        columns: ['whatsapp'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'delivery',
        index: 'delivery_destinationId_idx_1646ee5c',
        columns: ['destinationId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'delivery',
        index: 'delivery_managerId_idx_f8369ba6',
        columns: ['managerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'delivery',
        index: 'delivery_missionId_idx_25ef2118',
        columns: ['missionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'delivery',
        index: 'delivery_reservationId_idx_868923bb',
        columns: ['reservationId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'deliveryItem',
        index: 'deliveryItem_deliveryId_idx_ebc950f6',
        columns: ['deliveryId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'deliveryItem',
        index: 'deliveryItem_equipmentId_idx_e1548594',
        columns: ['equipmentId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'deliveryItem',
        index: 'deliveryItem_inventoryId_idx_367f33d0',
        columns: ['inventoryId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'equipment',
        index: 'equipment_categoryId_idx_15c304f2',
        columns: ['categoryId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'equipmentMaintenance',
        index: 'equipmentMaintenance_inventoryId_idx_367f33d0',
        columns: ['inventoryId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'equipmentMaintenance',
        index: 'equipmentMaintenance_inventoryId_status_idx_de327464',
        columns: ['inventoryId', 'status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'equipmentMaintenance',
        index: 'equipmentMaintenance_responsibleId_idx_cc071067',
        columns: ['responsibleId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'equipmentStatusHistory',
        index: 'equipmentStatusHistory_changedById_idx_d6e6aadb',
        columns: ['changedById'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'equipmentStatusHistory',
        index: 'equipmentStatusHistory_inventoryId_idx_367f33d0',
        columns: ['inventoryId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'formula',
        index: 'formula_serviceId_idx_b5d9acbf',
        columns: ['serviceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'galleryItem',
        index: 'galleryItem_galleryId_idx_28855aa4',
        columns: ['galleryId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'galleryItem',
        index: 'galleryItem_mediaId_idx_6b06655c',
        columns: ['mediaId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'importError',
        index: 'importError_importJobId_idx_84c20756',
        columns: ['importJobId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'inventory',
        index: 'inventory_equipmentId_idx_e1548594',
        columns: ['equipmentId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'inventory',
        index: 'inventory_storageLocationId_idx_8ecbb658',
        columns: ['storageLocationId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'inventoryAllocation',
        index: 'inventoryAllocation_inventoryId_idx_367f33d0',
        columns: ['inventoryId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'inventoryAllocation',
        index: 'inventoryAllocation_inventoryId_startDate_endDate_idx_6dc9d60c',
        columns: ['inventoryId', 'startDate', 'endDate'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'inventoryAllocation',
        index: 'inventoryAllocation_reservationId_idx_868923bb',
        columns: ['reservationId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'inventoryMovement',
        index: 'inventoryMovement_date_idx_b4ca319c',
        columns: ['date'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'inventoryMovement',
        index: 'inventoryMovement_fromStorageLocationId_idx_322d232d',
        columns: ['fromStorageLocationId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'inventoryMovement',
        index: 'inventoryMovement_inventoryId_idx_367f33d0',
        columns: ['inventoryId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'inventoryMovement',
        index: 'inventoryMovement_toStorageLocationId_idx_fb8fd303',
        columns: ['toStorageLocationId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'inventoryMovement',
        index: 'inventoryMovement_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'invoice',
        index: 'invoice_customerId_idx_b2a8a46c',
        columns: ['customerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'invoice',
        index: 'invoice_reservationId_idx_868923bb',
        columns: ['reservationId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'invoiceItem',
        index: 'invoiceItem_formulaId_idx_f318a8c4',
        columns: ['formulaId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'invoiceItem',
        index: 'invoiceItem_invoiceId_idx_d5c4f70e',
        columns: ['invoiceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'location',
        index: 'location_customerId_idx_b2a8a46c',
        columns: ['customerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'logisticsHistory',
        index: 'logisticsHistory_changedById_idx_d6e6aadb',
        columns: ['changedById'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'logisticsHistory',
        index: 'logisticsHistory_missionId_idx_25ef2118',
        columns: ['missionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'logisticsMission',
        index: 'logisticsMission_assignedUserId_idx_d0c6c9aa',
        columns: ['assignedUserId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'logisticsMission',
        index: 'logisticsMission_reservationId_idx_868923bb',
        columns: ['reservationId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'logisticsMission',
        index: 'logisticsMission_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'loyaltyAccount',
        index: 'loyaltyAccount_loyaltyLevelId_idx_3a7419c0',
        columns: ['loyaltyLevelId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'loyaltyTransaction',
        index: 'loyaltyTransaction_accountId_idx_cbfb3085',
        columns: ['accountId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'loyaltyTransaction',
        index: 'loyaltyTransaction_rewardId_idx_3d17b6e4',
        columns: ['rewardId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'notification',
        index: 'notification_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'notification',
        index: 'notification_userId_read_idx_76f3f2b6',
        columns: ['userId', 'read'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'paymentTransaction',
        index: 'paymentTransaction_paymentId_idx_b2fe9a10',
        columns: ['paymentId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'paymentTransactionHistory',
        index: 'paymentTransactionHistory_transactionId_idx_d3180832',
        columns: ['transactionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'refund',
        index: 'refund_paymentTransactionId_idx_762c9e15',
        columns: ['paymentTransactionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'reservation',
        index: 'reservation_customerId_idx_b2a8a46c',
        columns: ['customerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'reservation',
        index: 'reservation_locationId_idx_7aae3038',
        columns: ['locationId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'reservation',
        index: 'reservation_startDate_endDate_idx_c734dcfc',
        columns: ['startDate', 'endDate'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'reservation',
        index: 'reservation_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'reservationItem',
        index: 'reservationItem_formulaId_idx_f318a8c4',
        columns: ['formulaId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'reservationItem',
        index: 'reservationItem_reservationId_idx_868923bb',
        columns: ['reservationId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'reservationStatusHistory',
        index: 'reservationStatusHistory_changedById_idx_d6e6aadb',
        columns: ['changedById'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'reservationStatusHistory',
        index: 'reservationStatusHistory_reservationId_idx_868923bb',
        columns: ['reservationId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'rolePermission',
        index: 'rolePermission_permissionId_idx_f46fcdf5',
        columns: ['permissionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'rolePermission',
        index: 'rolePermission_roleId_idx_ffccc9a4',
        columns: ['roleId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'service',
        index: 'service_categoryId_idx_15c304f2',
        columns: ['categoryId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'serviceResource',
        index: 'serviceResource_equipmentId_idx_e1548594',
        columns: ['equipmentId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'serviceResource',
        index: 'serviceResource_formulaId_idx_f318a8c4',
        columns: ['formulaId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'userRoleAssignment',
        index: 'userRoleAssignment_roleId_idx_ffccc9a4',
        columns: ['roleId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'userRoleAssignment',
        index: 'userRoleAssignment_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'auditLog',
        foreignKey: {
          name: 'auditLog_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'delivery',
        foreignKey: {
          name: 'delivery_missionId_fkey',
          columns: ['missionId'],
          references: { schema: 'public', table: 'logisticsMission', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'delivery',
        foreignKey: {
          name: 'delivery_reservationId_fkey',
          columns: ['reservationId'],
          references: { schema: 'public', table: 'reservation', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'delivery',
        foreignKey: {
          name: 'delivery_destinationId_fkey',
          columns: ['destinationId'],
          references: { schema: 'public', table: 'location', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'delivery',
        foreignKey: {
          name: 'delivery_managerId_fkey',
          columns: ['managerId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'deliveryItem',
        foreignKey: {
          name: 'deliveryItem_deliveryId_fkey',
          columns: ['deliveryId'],
          references: { schema: 'public', table: 'delivery', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'deliveryItem',
        foreignKey: {
          name: 'deliveryItem_inventoryId_fkey',
          columns: ['inventoryId'],
          references: { schema: 'public', table: 'inventory', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'deliveryItem',
        foreignKey: {
          name: 'deliveryItem_equipmentId_fkey',
          columns: ['equipmentId'],
          references: { schema: 'public', table: 'equipment', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'equipment',
        foreignKey: {
          name: 'equipment_categoryId_fkey',
          columns: ['categoryId'],
          references: { schema: 'public', table: 'equipmentCategory', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'equipmentMaintenance',
        foreignKey: {
          name: 'equipmentMaintenance_inventoryId_fkey',
          columns: ['inventoryId'],
          references: { schema: 'public', table: 'inventory', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'equipmentMaintenance',
        foreignKey: {
          name: 'equipmentMaintenance_responsibleId_fkey',
          columns: ['responsibleId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'equipmentStatusHistory',
        foreignKey: {
          name: 'equipmentStatusHistory_inventoryId_fkey',
          columns: ['inventoryId'],
          references: { schema: 'public', table: 'inventory', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'equipmentStatusHistory',
        foreignKey: {
          name: 'equipmentStatusHistory_changedById_fkey',
          columns: ['changedById'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'formula',
        foreignKey: {
          name: 'formula_serviceId_fkey',
          columns: ['serviceId'],
          references: { schema: 'public', table: 'service', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'galleryItem',
        foreignKey: {
          name: 'galleryItem_galleryId_fkey',
          columns: ['galleryId'],
          references: { schema: 'public', table: 'gallery', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'galleryItem',
        foreignKey: {
          name: 'galleryItem_mediaId_fkey',
          columns: ['mediaId'],
          references: { schema: 'public', table: 'media', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'importError',
        foreignKey: {
          name: 'importError_importJobId_fkey',
          columns: ['importJobId'],
          references: { schema: 'public', table: 'importJob', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'inventory',
        foreignKey: {
          name: 'inventory_equipmentId_fkey',
          columns: ['equipmentId'],
          references: { schema: 'public', table: 'equipment', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'inventory',
        foreignKey: {
          name: 'inventory_storageLocationId_fkey',
          columns: ['storageLocationId'],
          references: { schema: 'public', table: 'storageLocation', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'inventoryAllocation',
        foreignKey: {
          name: 'inventoryAllocation_reservationId_fkey',
          columns: ['reservationId'],
          references: { schema: 'public', table: 'reservation', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'inventoryAllocation',
        foreignKey: {
          name: 'inventoryAllocation_inventoryId_fkey',
          columns: ['inventoryId'],
          references: { schema: 'public', table: 'inventory', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'inventoryMovement',
        foreignKey: {
          name: 'inventoryMovement_inventoryId_fkey',
          columns: ['inventoryId'],
          references: { schema: 'public', table: 'inventory', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'inventoryMovement',
        foreignKey: {
          name: 'inventoryMovement_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'inventoryMovement',
        foreignKey: {
          name: 'inventoryMovement_fromStorageLocationId_fkey',
          columns: ['fromStorageLocationId'],
          references: { schema: 'public', table: 'storageLocation', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'inventoryMovement',
        foreignKey: {
          name: 'inventoryMovement_toStorageLocationId_fkey',
          columns: ['toStorageLocationId'],
          references: { schema: 'public', table: 'storageLocation', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'invoice',
        foreignKey: {
          name: 'invoice_reservationId_fkey',
          columns: ['reservationId'],
          references: { schema: 'public', table: 'reservation', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'invoice',
        foreignKey: {
          name: 'invoice_customerId_fkey',
          columns: ['customerId'],
          references: { schema: 'public', table: 'customer', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'invoiceItem',
        foreignKey: {
          name: 'invoiceItem_invoiceId_fkey',
          columns: ['invoiceId'],
          references: { schema: 'public', table: 'invoice', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'invoiceItem',
        foreignKey: {
          name: 'invoiceItem_formulaId_fkey',
          columns: ['formulaId'],
          references: { schema: 'public', table: 'formula', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'location',
        foreignKey: {
          name: 'location_customerId_fkey',
          columns: ['customerId'],
          references: { schema: 'public', table: 'customer', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'logisticsHistory',
        foreignKey: {
          name: 'logisticsHistory_missionId_fkey',
          columns: ['missionId'],
          references: { schema: 'public', table: 'logisticsMission', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'logisticsHistory',
        foreignKey: {
          name: 'logisticsHistory_changedById_fkey',
          columns: ['changedById'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'logisticsMission',
        foreignKey: {
          name: 'logisticsMission_reservationId_fkey',
          columns: ['reservationId'],
          references: { schema: 'public', table: 'reservation', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'logisticsMission',
        foreignKey: {
          name: 'logisticsMission_assignedUserId_fkey',
          columns: ['assignedUserId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'loyaltyAccount',
        foreignKey: {
          name: 'loyaltyAccount_customerId_fkey',
          columns: ['customerId'],
          references: { schema: 'public', table: 'customer', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'loyaltyAccount',
        foreignKey: {
          name: 'loyaltyAccount_loyaltyLevelId_fkey',
          columns: ['loyaltyLevelId'],
          references: { schema: 'public', table: 'loyaltyLevel', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'loyaltyTransaction',
        foreignKey: {
          name: 'loyaltyTransaction_accountId_fkey',
          columns: ['accountId'],
          references: { schema: 'public', table: 'loyaltyAccount', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'loyaltyTransaction',
        foreignKey: {
          name: 'loyaltyTransaction_rewardId_fkey',
          columns: ['rewardId'],
          references: { schema: 'public', table: 'loyaltyReward', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'notification',
        foreignKey: {
          name: 'notification_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'payment',
        foreignKey: {
          name: 'payment_reservationId_fkey',
          columns: ['reservationId'],
          references: { schema: 'public', table: 'reservation', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'paymentTransaction',
        foreignKey: {
          name: 'paymentTransaction_paymentId_fkey',
          columns: ['paymentId'],
          references: { schema: 'public', table: 'payment', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'paymentTransactionHistory',
        foreignKey: {
          name: 'paymentTransactionHistory_transactionId_fkey',
          columns: ['transactionId'],
          references: { schema: 'public', table: 'paymentTransaction', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'refund',
        foreignKey: {
          name: 'refund_paymentTransactionId_fkey',
          columns: ['paymentTransactionId'],
          references: { schema: 'public', table: 'paymentTransaction', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'reservation',
        foreignKey: {
          name: 'reservation_customerId_fkey',
          columns: ['customerId'],
          references: { schema: 'public', table: 'customer', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'reservation',
        foreignKey: {
          name: 'reservation_locationId_fkey',
          columns: ['locationId'],
          references: { schema: 'public', table: 'location', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'reservationItem',
        foreignKey: {
          name: 'reservationItem_reservationId_fkey',
          columns: ['reservationId'],
          references: { schema: 'public', table: 'reservation', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'reservationItem',
        foreignKey: {
          name: 'reservationItem_formulaId_fkey',
          columns: ['formulaId'],
          references: { schema: 'public', table: 'formula', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'reservationStatusHistory',
        foreignKey: {
          name: 'reservationStatusHistory_reservationId_fkey',
          columns: ['reservationId'],
          references: { schema: 'public', table: 'reservation', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'reservationStatusHistory',
        foreignKey: {
          name: 'reservationStatusHistory_changedById_fkey',
          columns: ['changedById'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'rolePermission',
        foreignKey: {
          name: 'rolePermission_roleId_fkey',
          columns: ['roleId'],
          references: { schema: 'public', table: 'role', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'rolePermission',
        foreignKey: {
          name: 'rolePermission_permissionId_fkey',
          columns: ['permissionId'],
          references: { schema: 'public', table: 'permission', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'service',
        foreignKey: {
          name: 'service_categoryId_fkey',
          columns: ['categoryId'],
          references: { schema: 'public', table: 'serviceCategory', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'serviceResource',
        foreignKey: {
          name: 'serviceResource_formulaId_fkey',
          columns: ['formulaId'],
          references: { schema: 'public', table: 'formula', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'serviceResource',
        foreignKey: {
          name: 'serviceResource_equipmentId_fkey',
          columns: ['equipmentId'],
          references: { schema: 'public', table: 'equipment', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'user',
        foreignKey: {
          name: 'user_customerId_fkey',
          columns: ['customerId'],
          references: { schema: 'public', table: 'customer', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'userRoleAssignment',
        foreignKey: {
          name: 'userRoleAssignment_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'userRoleAssignment',
        foreignKey: {
          name: 'userRoleAssignment_roleId_fkey',
          columns: ['roleId'],
          references: { schema: 'public', table: 'role', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
    ];
  }
}

MigrationCLI.run(import.meta.url, M);
